theme: jekyll-theme-leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: AWS Certified Developer - Associate (DVA-C01) Exam Notes
description: Notes based on Stéphane Maarek's Udemy course.
nav_order: 4